### PR TITLE
add screenshot

### PR DESCRIPTION
**Pull request by jospoortvliet**
Signed-off-by: Jos Poortvliet <jospoortvliet@gmail.com>

### CODE REVIEW

**Comment by nickvergessen** [comment]
That is not what this app does ;)

**Comment by nickvergessen** [comment]
Replaced with #13

**Comment by nickvergessen** [comment]
Published: https://apps.nextcloud.com/apps/quota_warning

**Comment by jospoortvliet** [comment]
My mistake, thanks!

**Pull request closed without merging**
